name: flutter_facebook_appevents
description: flutter_facebook_appevents integrates Facebook App Events to your Flutter app.
version: 0.2.0
homepage: https://github.com/zonble/flutter_facebook_appevents

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ">=1.0.0 <5.0.0"
  import_sorter: 4.6.0
  pubspec_dependency_sorter: 1.0.5
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: net.zonble.flutter_facebook_appevents
        pluginClass: FlutterFacebookAppeventsPlugin
      ios:
        pluginClass: FlutterFacebookAppeventsPlugin
