name: Build
on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        version: ["3.24.x"]
        include:
          - os: macOS-latest
            TARGET: macos
          - os: ubuntu-latest
            TARGET: linux
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          channel: "stable" # optional, default to: 'stable'
      - run: flutter pub get
        working-directory: ./example
      - name: Build Android APK
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          flutter doctor
          flutter build apk --debug
        working-directory: ./example
      - name: Build iOS App
        if: startsWith(matrix.os, 'macOS')
        run: |
          flutter doctor
          flutter build ios --debug --no-codesign
        working-directory: ./example
